theme: jekyll-theme-leap-day
title: Delivered Technologies
description: The Home of RuleBook
tagline: Simplifying Software
github:
  repository_url: https://github.com/rulebook-rules/rulebook
  repository_name: RuleBook
  javadocs_url: /rulebook/javadocs/
